AppBundle\Entity\Groups:
    type: entity
    table: groups
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        permissions:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
